users/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

from . import views

app_name='users'

urlpatterns = [
    path('signup', views.SignupView, name='signup'),
    path('login', views.LogInView, name='login'),
    path('da', views.dashboard, name='da'),
    path('logout', views.LogOutUser, name='logout'),
    #path('admin', views.AdminView, name='admin'),
    path('listuser', views.ListUsers, name='listuser' ),
    path('password_reset_form', views.password_reset, name='password_reset_form' ),
    path('delete', views.delete, name='delete'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/delete.html
<style>
    select {
        margin: 50px;
        width: auto;
        padding: 0px 40px 5px 40px;
        font-size: 10px;
        border: solid #CCC;
        height: 43px;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 10px;
        text-align:center;
    }
</style>
{% extends "users/index.html" %}

<body>
  
{% block content %}
    <!-- Page Heading -->
    <div id="content-wrapper" class="d-flex flex-column">
        <div class="d-sm-flex align-items-center justify-content-between mb-4" style="margin-left: 45px;">
            <h1 class="h3 mb-0 text-gray-800">Delete User</h1>

        </div>
        <form name="getfilename" method="POST" style="margin-left: 50px;" action="{% url 'users:delete' %}">
            {% csrf_token %}
            <div>
                <p class="form-box">
                
                    <label for="user_sel" >Select a user to delete:</label>
                    
                    <select name="user_sel" id="user" class="selectpicker show-tick form-select form-select-sm" data-live-search="true" data-size="5" multiple data-actions-box="true" data-width="30%" style="margin-left: 100px;">
                        
                        {% for row in users_all %}
                    
                            <option style="color:rgb(118, 111, 111)"  value={{row.email}} > {{row.email}}

                        {% endfor %}
                            
                    </select>
                    
                    <button type="submit" name="delete" style="margin-left: 40px; height:40px; width: 160px; font-size:16px; border-radius: 10px;" text-align="center;" padding="35px 52px;" class="btn btn-outline-secondary btn-sm">Delete</button>

                </p>
            </div>
            <br><br><br><br><br><br><br><br><br>
        </form>
    </div>

{% endblock %}

templates/home.html
{% load static %}
<html lang="en">
    
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>VARA Tool</title>
    
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
    <link
        href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i'}"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

</head>
<body class="bg-gradient-primary">

  <div class="container">

      <!-- Outer Row -->
      <div class="row justify-content-center">

          <div class="col-xl-10 col-lg-12 col-md-9">

              <div class="card o-hidden border-0 shadow-lg my-5">
                  <div class="card-body p-0">
                      <!-- Nested Row within Card Body -->
                      <div class="row">
                          <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                          <div class="col-lg-6">
                              <div class="p-5">
                                  <div class="text-center">
    
                                    <br>
                                    <br>
                                    <br>
                                    <h3 class="login-heading mb-4">Welcome to VARA Tools!</h3>            
                                    <br>
                                    <br>
                                         
                                    
                                    <h4>If you are registered please click </h4>
                                    <h4><a href="{% url 'users:login' %}">Signin</a></h4> 
                                      
                                    <br>
                                    <br>

                                    <h4>If you are forgot your password please click </h4>
                                    <h4><a href="{% url 'users:password_reset_form' %}">Reset Password</a></h4> 
                                    <br>
                                  
                                    <h4>If not registered!</h4>
                                    <div class="form-group last mb-4">
                                    <div><h4>Please contact your admin </h4></div>
                                    
                                    </div>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    
                                  </div>
                              </div>
                          </div>
                        </div>
                  </div>
            </div>
      </div>

  </div>
     
    
  </body>
</html>

templates/list_user.html
{% extends "users/index.html" %}
<body>
  
{% block content %}

<div class="container-fluid">  
  <div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary"> Listed Users </h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">       
          <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <div class="row">
              <div class="col-sm-12 col-md-6">
                <div class="dataTables_length" id="dataTable_length">
                  <label>Show 
                    <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm">
                      <option value="10">10</option>
                      <option value="25">25</option>
                      <option value="50">50</option>
                      <option value="100">100</option>
                    </select> 
                  entries</label>
                </div>
              </div>
              <div class="col-sm-12 col-md-6">
                <div id="dataTable_filter" class="dataTables_filter">
                  <label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label>
                </div>
              </div>
            </div>
          
            <table class="table table-bordered table-hover" id="tabledata" width="100%" cellspacing="0">
            
              <thead class="table-primary">
                <tr role="row">
                  <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="User Email: activate to sort column descending" style="width: 74px;">User Email</th>
                  <th>Username</th>
                  <th>Superuser</th>
                  <th>Engineer</th>
                  <th>Manager</th>
                  
                </tr>
              </thead>
              <tbody>
                {% for user in users %}  
                  <tr>
                    <td>{{user.email}}</td>
                    <td>{{user.username}}</td>
                    <td>{{user.is_superuser}}</td>
                    <td>{{user.is_engineer}}</td>
                    <td>{{user.is_manager}}</td>
                    <td><a href="listuser/{{ user.email }} " id="demo">delete</a></td>
                  </tr>
                  {% endfor %} 
              </tbody>
          
            </table>	

            <script>
              document.getElementById("demo").addEventListener("click", myFunction)
              function myFunction() {
                alert("{{ user.email }} removed from the users!")
              }
            </script>

              {% if pages.has_other_pages %}
              <nav aria-label="...">
                <ul class="pagination pagination-sm">
                  {% if pages.has_previous %}
                    <li><a href="?page={{ pages.previous_page_number }}" class="page-link">&laquo;</a></li>
                  {% else %}
                    <li class="disabled" ><span class="page-link">&laquo;</span></li>
                  {% endif %}
                  {% for i in pages.paginator.page_range %}
                    {% if pages.number == i %}
                      <li class="active" ><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                      <li><a href="?page={{ i }}"  class="page-link">{{ i }}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if users.has_next %}
                    <li><a href="?page={{ pages.next_page_number }}" class="page-link">&raquo;</a></li>
                  {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                  {% endif %}
                </ul>
              </nav>
              {% endif %}
    </div>
        </div>
  </div>
</div>
</div>
    
    

</body>
{% endblock %}